// Code generated by tygo. DO NOT EDIT.

//////////
// source: dto.go
/*
Package apidto is sakms's curated, exported request/response DTO
boundary for the future frontend's generated TypeScript API client (see
.omc/plans/frontend-redesign-seerr.md, Stage 0 / Guardrail #4).

Why this package exists: today's handlers decode/encode JSON using
unexported request structs (e.g. internal/api's upsertConnectionRequest)
and raw internal/domain structs (e.g. tmdb.Item, connections.Summary)
encoded directly. A source-parsing codegen tool CAN see unexported types
if pointed at internal/api directly, but that would emit a TypeScript
type for every internal handler struct across the whole package — far
more than a frontend client should ever import, and it would silently
change shape every time an unrelated handler's internal request struct
changed. This package is the deliberate alternative: a small, hand-picked,
EXPORTED set of types that mirror only what a frontend actually needs to
send/receive, kept in one place a codegen tool can be pointed at in
isolation (see internal/apidto/gen).

Scope (Stage 0 / Stage 1 only — see README.md "Scope grows per stage"):
auth boot (setup/login/status/mode/OIDC config/API key management) and
Discover's read-only surface (poster items + availability badges), the
exact set Stage 1's toolchain slice consumes. Stages 2-4 add their own
DTOs here as their frontend work lands — this file is a starting point,
not a final inventory, per Guardrail #4.

These types are currently PARALLEL COPIES of the shapes already produced
by internal/api's handlers (authStatusResponse, oidcStatusResponse,
tmdb.Item, etc.) and internal/auth's APIKeyStatus. Stage 0 defines them
but does not wire any handler to use them — no frontend exists yet to
prove a wiring change against, and touching the auth handlers here would
add lockout risk for zero benefit (see README.md). Stage 1 is expected to
converge the real handlers onto these exact types, at which point the
parallel definitions in internal/api collapse into a single source of
truth here.

Field names, JSON tags, and types below match the current wire format
exactly (same lowerCamelCase JSON keys the existing handlers already
emit) so that a future Stage-1 handler swap is a type substitution, not a
wire-format change.

IMPORTANT — three-state optional-secret fields (Guardrail #5): see
ConnectionUpsertRequest.APIKey's doc comment and README.md's "Three-state
secret mapping rule" section before generating or consuming a TypeScript
client for any *string field in this package.
*/

/**
 * SetupRequest is the body of POST /api/auth/setup — SAK's one-time,
 * first-run login bootstrap. Mode selects the auth strategy ("password" is
 * the default when Mode is omitted, "oidc", or "none").
 * AcknowledgeInsecure must be true to select Mode "none". The four
 * OIDC* fields are required together, and only meaningful, when
 * Mode == "oidc".
 */
export interface SetupRequest {
  username: string;
  password: string;
  mode: string;
  acknowledgeInsecure: boolean;
  oidcIssuerUrl?: string;
  oidcClientId?: string;
  oidcClientSecret?: string;
  oidcRedirectUrl?: string;
}
/**
 * SetupResponse is returned by POST /api/auth/setup only for "oidc"-mode
 * setup (empty body / 204 for "password"/"none"). Exactly one of APIKey or
 * APIKeyNote is populated: APIKey is a one-time break-glass credential
 * revealed ONCE, never retrievable again; APIKeyNote is present instead
 * when SAKMS_API_KEY is set via environment (no settings-managed key is
 * minted in that case — the env value IS the break-glass credential).
 */
export interface SetupResponse {
  apiKey?: string;
  apiKeyNote?: string;
}
/**
 * LoginRequest is the body of POST /api/auth/login — only meaningful when
 * the active auth mode is "password" (checked server-side; "oidc" logs in
 * via a full-page redirect to /api/auth/oidc/login instead, and "none" has
 * no login step).
 */
export interface LoginRequest {
  username: string;
  password: string;
}
/**
 * AuthStatusResponse is GET /api/auth/status's response — the one call the
 * frontend's boot sequence makes before it knows anything else about the
 * instance, deciding between the setup wizard, the login screen, and the
 * app (see Guardrail #2's 3-way boot branch). Mode is one of "password",
 * "oidc", or "none".
 */
export interface AuthStatusResponse {
  configured: boolean;
  authenticated: boolean;
  mode: string;
}
/**
 * AuthModeResponse is GET /api/auth/mode's response.
 */
export interface AuthModeResponse {
  mode: string;
}
/**
 * AuthModeRequest is PUT /api/auth/mode's body — switches the ALREADY
 * authenticated operator's active auth mode. AcknowledgeInsecure must be
 * true to switch into "none" (mirrors SetupRequest's same field for the
 * first-run case).
 */
export interface AuthModeRequest {
  mode: string;
  acknowledgeInsecure: boolean;
}
/**
 * OIDCStatusResponse is GET /api/auth/oidc's response. HasSecret reports
 * whether a client secret is currently stored; the secret itself is NEVER
 * returned (mirrors ConnectionSummary's HasAPIKey/KeySuffix pattern for the
 * same reason — see README.md).
 */
export interface OIDCStatusResponse {
  issuerUrl: string;
  clientId: string;
  redirectUrl: string;
  hasSecret: boolean;
}
/**
 * OIDCConfigRequest is PUT /api/auth/oidc's body — sets/replaces the
 * OIDC provider config for an already-configured instance. Unlike
 * ConnectionUpsertRequest.APIKey, ClientSecret here is a plain (non-pointer)
 * required field: every PUT to this endpoint must supply the full config,
 * there is no "leave secret unchanged" partial-update mode for OIDC config
 * today.
 */
export interface OIDCConfigRequest {
  issuerUrl: string;
  clientId: string;
  clientSecret: string;
  redirectUrl: string;
}
/**
 * APIKeyStatusResponse is GET /api/apikey's response. Source is one of
 * "env" (SAKMS_API_KEY active), "settings" (a regenerated key is stored),
 * or "none" (no key exists). The key itself is never returned here — only
 * KeySuffix, matching ConnectionSummary's masked-display convention.
 */
export interface APIKeyStatusResponse {
  hasKey: boolean;
  keySuffix?: string;
  source: string;
}
/**
 * APIKeyRegenerateResponse is POST /api/apikey/regenerate's response — the
 * one place the full API key crosses the API boundary. Shown once, never
 * retrievable again afterward (same one-shot-reveal contract as
 * SetupResponse.APIKey).
 */
export interface APIKeyRegenerateResponse {
  apiKey: string;
  keySuffix: string;
}
/**
 * ModeStatus reports what's configured for one mode (Mode is one of
 * "movies", "series", "adult") — enough for the setup wizard to know which
 * steps are already done and skip past them.
 */
export interface ModeStatus {
  mode: string;
  available: boolean;
  arrConfigured: boolean;
  allowlistCount: number /* int */;
}
/**
 * SetupStatusResponse is GET /api/setup/status's response — a pure read
 * model over what's already configured, driving whether the setup wizard
 * shows itself at all and which of its steps it can skip.
 */
export interface SetupStatusResponse {
  modes: ModeStatus[];
  jellyfinConfigured: boolean;
  ollamaConfigured: boolean;
  dismissed: boolean;
  anyConfigured: boolean;
}
/**
 * DismissSetupRequest is PUT /api/setup/dismissed's body.
 */
export interface DismissSetupRequest {
  dismissed: boolean;
}
/**
 * DiscoverItem is one TMDB trending/popular result for Movies/Series
 * Discover (GET /api/modes/{mode}/discover) — mirrors tmdb.Item's exact
 * wire shape. MediaType is "movie" or "tv".
 */
export interface DiscoverItem {
  id: number /* int */;
  title: string;
  posterPath: string;
  overview: string;
  releaseDate: string;
  voteAverage: number /* float64 */;
  mediaType: string;
}
/**
 * AdultDiscoverItem is one TPDB scene result for Adult Discover
 * (GET /api/modes/adult/discover) — scene-shaped, not title-shaped (Studio
 * substitutes for a studio/site name). Date is TPDB's release date string,
 * unparsed. Image is the scene thumbnail URL served from TPDB's own image CDN
 * (cdn.theporndb.net); it is frequently empty (many scenes have no art), so
 * the client must render a text-only card when blank and route non-empty
 * values through the image proxy (GET /api/images/proxy?url=), never
 * hot-linking TPDB directly (plan Decision #7). DurationSeconds is the
 * scene's pre-grab runtime in seconds (see internal/tpdbrest.Scene.Duration
 * for sourcing/confidence: documented-shape + corroborated by two
 * independent sources, not live-confirmed against a real TPDB instance); it
 * may be 0 (unknown), which the auto-grab bitrate scorer (Stage 2) must
 * treat as "skip the pre-grab bitrate check," never a real zero-length
 * runtime or a divide-by-zero input.
 */
export interface AdultDiscoverItem {
  id: string;
  title: string;
  studio: string;
  date: string;
  image: string;
  durationSeconds: number /* int */;
}
/**
 * AvailabilityResponse is GET /api/modes/{mode}/availability's response —
 * backs a Discover card's availability badge (Stage 1 scope: "poster cards
 * with availability badges" per the plan). CheckedAt is an RFC3339Nano
 * timestamp of when the probe ran.
 */
export interface AvailabilityResponse {
  available: boolean;
  releaseCount: number /* int */;
  checkedAt: string;
}
/**
 * ConnectionSummary is one entry of GET /api/connections's response — what's
 * safe to expose about a configured connection: never the secret itself,
 * only whether one is set and its last 4 characters (masked display).
 * Included here alongside ConnectionUpsertRequest even though the
 * Connections/Settings UI itself isn't built until Stage 4 — see
 * ConnectionUpsertRequest's doc comment for why.
 */
export interface ConnectionSummary {
  service: string;
  url: string;
  username?: string;
  hasApiKey: boolean;
  keySuffix?: string;
  updatedAt: string;
}
/**
 * ConnectionUpsertRequest is PUT /api/connections/{service}'s body —
 * included in Stage 0's curated set (ahead of Stage 4, when Settings'
 * actual frontend lands) specifically BECAUSE it carries the single most
 * safety-critical mapping rule in this whole DTO boundary (Guardrail #5)
 * and needed to be proven against the chosen codegen tool before that tool
 * choice was finalized, not discovered as a surprise in Stage 4.
 * APIKey is a pointer so the three states a client MUST be able to express
 * survive the JSON round-trip (json.Decode sets it accordingly; omitempty
 * only affects marshaling, never decoding):
 *   - field ABSENT from the request body entirely (nil)  → preserve the
 *     stored secret. The server never sends the real secret back to a
 *     client (see ConnectionSummary above — only HasAPIKey/KeySuffix are
 *     exposed), so an untouched, blank key input MUST be omitted from the
 *     JSON body, never sent as "".
 *   - field present as ""  (&"")                          → explicitly
 *     clear the stored secret (e.g. switching to a service that needs
 *     none, like Ollama).
 *   - field present, non-empty  (&"sk-...")                → set/replace
 *     the stored secret.
 * TypeScript CANNOT express this three-way distinction as a type — both
 * a field absent entirely and a field present with an empty-string value
 * collapse to the same `string | undefined` a source-parsing generator
 * emits for a Go *string.
 * See README.md's "Three-state secret mapping rule" section for the
 * generated TypeScript shape and the load-bearing prose rule a frontend
 * MUST follow by convention (not by the type system) when building this
 * request body.
 */
export interface ConnectionUpsertRequest {
  url: string;
  username?: string;
  apiKey?: string;
}
